[test]
levels = ["syntax", "install", "registration", "instantiation", "execution"]
publish = 'true'

[test.workflows]
cpu = ['apply_animation','skeleton_comparison','rigged_manipulator']
gpu = ["mia_humanoid","unirig_bird","unirig_humanoid"]

[test.platforms]
# CPU platforms
linux = true
macos = true
windows = true
windows_portable = true
linux_gpu = true
windows_gpu = true
windows_portable_gpu = true
macos_desktop = true
windows_desktop = true
windows_desktop_gpu = true
